nest g resource dashboard
nest g resource products
nest g resource types
nest g resource collectors
nest g resource categories
nest g resource economical_activities
nest g resource personal_status
nest g resource localities
nest g resource clients
nest g resource agents
nest g resource users
nest g resource auth
nest g resource customers_accounts
nest g resource customers_cards
nest g resource collections
nest g resource cash
nest g resource customers_activities
nest g resource collectors_activities
nest g resource satisfied_customers_cards
nest g resource types_statistics
nest g resource products_statistics
nest g resource products_forecasts
nest g resource transfers
nest g resource stocks